import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [userUID, setuserUID] = useState<string>('');
  const ChangeUID = (e:object) => { setuserUID(e.target.value); }


  const onSubmitHandler = () => {

  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"w-screen h-screen relative bg-violet-200"}>
        <div className={"body absolute z-10"}>
          <div className='w-full h-3/5 flex items-end justify-center'>
            <div className={'w-full' }>
              <Image
                className='m-auto'
                src={"/../public/logo-genshin.png"}
                alt={"background Image for home"}
                width={900}
                height={200}
              />
            </div>
          </div>
          <form className='w-96 m-auto rounded-md bg-white opacity-90' onSubmit={onSubmitHandler}>
            <input 
                className={'w-80 h-14 text-center text-3xl rounded-md'}
                type={'number'}
                placeholder={"UID"}
                value={userUID}
                onChange={ChangeUID}
              />
            <button className='w-16 h-14 text-3xl'> > </button>
          </form>
        </div>
      </main>
    </>
  )
}
