import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [userUID, setuserUID] = useState<string>('');

  const ChangeUID = (e:object) => { 
    if(e.target.value.length > 9){ e.target.value = e.target.value.substr(0, 9); }
    setuserUID(e.target.value); 
  }


  const onSubmitHandler = async(e) => {
    // fatch 진행필요!
    e.preventDefault();
    try{
      const datas = { userUID: userUID }
      const res = await axios.post('/api/getUser', datas);
      if(res.statusText === "OK"){
        console.log(res.data.result);
      }
    }catch(error){ console.log("error ===> ", error) }
    
    // try{
    //   let url = "/api/getUser";
    //   const res = await fetch(url, {
		// 		timeout: 1000,		// 1초 타임아웃 제한..
		// 		method: "POST",
		// 		headers: { "Content-Type": "application/json;charset=utf-8" },
    //     body: datas,
		// 	})
    //   if(res.ok){
    //     const data = await res.json();
    //     console.log(data.result);
    //   }
    // }catch(error) { console.log("error ===> ", error) }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"w-screen h-screen relative bg-violet-200"}>
        <div className={"body absolute z-10"}>
          <div className='w-full h-3/5 flex items-end justify-center'>
            <div className={'w-full' }>
              <Image
                className='m-auto'
                src={"/../public/logo-genshin.png"}
                alt={"background Image for home"}
                width={900}
                height={200}
              />
            </div>
          </div>
          <form className='w-96 m-auto rounded-md bg-white opacity-90' onSubmit={onSubmitHandler}>
            <input 
                className={'w-80 h-14 text-center text-3xl rounded-md'}
                type={'number'}
                placeholder={"UID"}
                value={userUID}
                onChange={ChangeUID}
                maxLength={9}
              />
            <button className='w-16 h-14 text-3xl'> > </button>
          </form>
        </div>
      </main>
    </>
  )
}
