import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex h-screen flex-col'}>
        <Link className="w-1/10 h-1/10 min-h-20 bg-red-600 fixed" href="/">
          RootLayout
        </Link>
        {children}
      </body>
    </html>
  );
}
